
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.network "forwarded_port", guest: 80, host: 3000
    config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.synced_folder "../project", "/var/www/html/project", :mount_options => ['dmode=777', 'fmode=777']
    config.vm.provision :shell, :inline => "sed -i 's/us.archive/de.archive/g' /etc/apt/sources.list"

    config.vm.provision :shell, path: "script/1_bootstrap.sh"
    config.vm.provision :shell, path: "script/2_install_lamp.sh"

    config.vm.provider "virtualbox" do |v|
      # v.gui = true
      v.memory = 2048
      v.cpus = 2
    end

end
