
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "33.33.33.1"

    config.vm.synced_folder "../project", "/home/vagrant/project"
    config.vm.provision :shell, path: "script/bootstrap.sh"
    config.vm.provision :shell, :inline => "sed -i 's/us.archive/de.archive/g' /etc/apt/sources.list"

end
